version: '3'
services:
  php:
    image: php:apache
    container_name: php-app
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      - 443:443
  mysql: 
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=OhpwdzIJZfRJbrw1OJ+0MHz9Jc2P
      - MYSQL_DATABASE=db_rentalmobil
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=34yJYqIgSDZ9qNULklw746UPI08k
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # True
    ports:
      - 3306:3306
    volumes:
      - "./db:/var/lib/mysql" # persist a sql db even when container stops
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=34yJYqIgSDZ9qNULklw746UPI08k
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
networks:
  car-rental-network:
    external: true